# Generated by Django 4.0.3 on 2022-03-13 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('alias', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=72)),
                ('birthday', models.TextField(default='')),
                ('history', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pks', models.ManyToManyField(related_name='pokers', to='acceso.usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes_given', to='acceso.usuario')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokes_received', to='acceso.usuario')),
            ],
        ),
    ]
